language: ruby
cache: bundler

install:
  - bundle install
script: jekyll build
after_success:
  - npm install --global surge
  - chmod ugo+x ./_scripts/deploy.sh
  - ./_scripts/deploy.sh

sudo: false
notifications:
  email: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_API_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  keep-history: false
#  repo: newNHSHackdaySite/newNHSHackdaySite.github.io
#  on:
#    branch: master